apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dvr

resources:
  - ../../base/

images:
  - name: app
    newName: ghcr.io/autobrr/autobrr
    newTag: latest@sha256:b666903f1bba48e380b211da779ffd89f34f8ebfa2f32b1c4b1e60f8882df2bf

configMapGenerator:
  - name: env-configmap
    literals:
      - PUID=911
      - PGID=911
      - TZ=Europe/Amsterdam

namePrefix: autobrr-

labels:
  - includeSelectors: true
    pairs:
      app: autobrr

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
  - path: ingress-patch.yaml
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: autobrr
    target:
      kind: Deployment
      name: deployment
