apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dvr

resources:
  - ../../base/

images:
  - name: app
    newName: ghcr.io/autobrr/autobrr
    newTag: latest@sha256:7e8ce4ec9397685762dc7d8426c976cb15bd36522fac91dfd3648a4c57c6d358

configMapGenerator:
  - name: env-configmap
    literals:
      - PUID=911
      - PGID=911
      - TZ=Europe/Amsterdam

namePrefix: autobrr-

labels:
  - includeSelectors: true
    pairs:
      app: autobrr

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
  - path: ingress-patch.yaml
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: autobrr
    target:
      kind: Deployment
      name: deployment
