apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddns-route53
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: ddns-route53
            app.kubernetes.io/name: ddns-route53
        spec:
          restartPolicy: Never
          containers:
            - name: ddns-route53
              image: ghcr.io/crazy-max/ddns-route53:latest@sha256:d2196f236afbc61d805bbcf11142f6a7bbedb14df999070f0be49fe638add1a7
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: ddns-route53-envs
              env:
                - name: TZ
                  value: "Europe/Amsterdam"
                - name: LOG_LEVEL
                  value: info
                - name: LOG_JSON
                  value: "true"
              volumeMounts:
                - name: secret-volume
                  readOnly: true
                  mountPath: "/ddns-route53.yml"
                  subPath: ddns-route53.yml
          volumes:
            - name: secret-volume
              secret:
                secretName: route-53-credentials-ddns
