apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddns-route53
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: ddns-route53
              image: ghcr.io/crazy-max/ddns-route53:latest@sha256:34edab2d59208f72e4f5ec6618e4347e1bfd751a66d3de8542cd64c2e2d3bac2
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: ddns-route53-envs
              env:
                - name: TZ
                  value: "Europe/Amsterdam"
                - name: LOG_LEVEL
                  value: info
                - name: LOG_JSON
                  value: "true"
              volumeMounts:
                - name: secret-volume
                  readOnly: true
                  mountPath: "/ddns-route53.yml"
                  subPath: ddns-route53.yml
          volumes:
            - name: secret-volume
              secret:
                secretName: route-53-credentials-ddns
