apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/
  - secret.yaml

images:
  - name: app
    newName: ghcr.io/blakeblackshear/frigate
    newTag: 0.17.0@sha256:5be5ce3b79f8b09a52957afea9d4a23ad62c9f077a05d9047e3404eb78c304a8

namespace: smarthome

namePrefix: frigate-

labels:
  - includeSelectors: true
    pairs:
      app: frigate

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
  - path: ingress-patch.yaml
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: frigate
    target:
      kind: Deployment
      name: deployment

configMapGenerator:
  - name: frigate-configmap
    files:
      - config.yml=./resources/config.yml
