apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dvr

resources:
  - ../../base/

images:
  - name: app
    newName: ghcr.io/alexta69/metube
    newTag: latest@sha256:cd226eedd357697ab2efd4b5e7c5221e973326d210c1e3abc08687d58d97088c

configMapGenerator:
  - name: env-configmap
    literals:
      - UID=911
      - GID=911
      - AUDIO_DOWNLOAD_DIR=/downloads/music/livesets
      - DEFAULT_THEME=dark
      - TEMP_DIR=/dlcache
      - DEFAULT_OPTION_PLAYLIST_STRICT_MODE=true

namePrefix: metube-

labels:
  - includeSelectors: true
    pairs:
      app: metube
  - pairs:
      app.kubernetes.io/name: metube

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
  - path: ingress-patch.yaml
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: metube
    target:
      kind: Deployment
      name: deployment
