apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dvr

resources:
  - ../../base/

images:
  - name: app
    newName: ghcr.io/alexta69/metube
    newTag: latest@sha256:eba7a85e71f9b49f1a699e7fd90f3cef855af25fa2395c1c241af39ec48e4b1a

configMapGenerator:
  - name: env-configmap
    literals:
      - UID=911
      - GID=911
      - AUDIO_DOWNLOAD_DIR=/downloads/music/livesets
      - DEFAULT_THEME=dark
      - TEMP_DIR=/dlcache
      - DEFAULT_OPTION_PLAYLIST_STRICT_MODE=true

namePrefix: metube-

labels:
  - includeSelectors: true
    pairs:
      app: metube

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
  - path: ingress-patch.yaml
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: metube
    target:
      kind: Deployment
      name: deployment
