apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dvr

resources:
  - ../../base/

images:
  - name: app
    newName: ghcr.io/alexta69/metube
    newTag: latest@sha256:3de82b0a8c1339a501e0b6ac00e8fa65676144c9ef78f7cc0b6003348d01a97f

configMapGenerator:
  - name: env-configmap
    literals:
      - UID=911
      - GID=911
      - AUDIO_DOWNLOAD_DIR=/downloads/music/livesets
      - DEFAULT_THEME=dark
      - TEMP_DIR=/dlcache
      - DEFAULT_OPTION_PLAYLIST_STRICT_MODE=true

namePrefix: metube-

labels:
  - includeSelectors: true
    pairs:
      app: metube

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
  - path: ingress-patch.yaml
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: metube
    target:
      kind: Deployment
      name: deployment
