excludeNamespaces: "kube-system,trivy-system"

operator:
  scanJobsConcurrentLimit: 1
  scanJobTTL: "10m"
  builtInTrivyServer: true

trivy:
  server:
    replicas: 1
    extraServerVolumes:
      volumes:
        - name: dotcache
          emptyDir: {}
      volumeMounts:
        - name: dotcache
          mountPath: /.cache

serviceMonitor:
  enabled: true
