apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redlib

resources:
  - ns.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - envs:
      - ./resources/redlib.env
    name: redlib-envs
