apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dvr

resources:
  - ../../base/

images:
  - name: app
    newName: ghcr.io/linuxserver/bazarr
    newTag: 1.6.2@sha256:8b30e81c4aec2991f469e78fae8afaa89ecc9b21a80e3897f50427216b55470c

configMapGenerator:
  - name: env-configmap
    literals:
      - PUID=911
      - PGID=911
      - TZ=Europe/Amsterdam

namePrefix: bazarr-1080-

labels:
  - includeSelectors: true
    pairs:
      app: bazarr-1080
  - pairs:
      app.kubernetes.io/name: bazarr-1080

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
  - path: ingress-patch.yaml
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: bazarr-1080
    target:
      kind: Deployment
      name: deployment
