apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dvr

resources:
  - ../../base/

images:
  - name: app
    newName: ghcr.io/linuxserver/bazarr
    newTag: 1.5.6@sha256:d736df5df0286373a26d34f47aa413cb8aeada74f6338dac372a6d37ba1b3b0d

configMapGenerator:
  - name: env-configmap
    literals:
      - PUID=911
      - PGID=911
      - TZ=Europe/Amsterdam

namePrefix: bazarr-1080-

labels:
  - includeSelectors: true
    pairs:
      app: bazarr-1080

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
  - path: ingress-patch.yaml
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: bazarr-1080
    target:
      kind: Deployment
      name: deployment
