apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nutritrace
  name: nutritrace
  namespace: nutritrace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nutritrace
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nutritrace
    spec:
      containers:
        - name: nutritrace
          image: ghcr.io/traceapps/nutritrace:dev@sha256:ff95a8304941b6db269e12669a7849f03576a59bd6b3c92bc3008ef364aa0b65
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: nutritrace-config
            - secretRef:
                name: nutritrace-credentials
          ports:
            - containerPort: 3001
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: db
            - mountPath: /data/uploads
              name: uploads
      restartPolicy: Always
      volumes:
        - name: db
          hostPath:
            path: /config/nutritrace/db
            type: DirectoryOrCreate
        - name: uploads
          hostPath:
            path: /config/nutritrace/uploads
            type: DirectoryOrCreate
