apiVersion: apps/v1
kind: Deployment
metadata:
  name: kromgo
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: kromgo
  replicas: 1
  template:
    metadata:
      labels:
        app: kromgo
    spec:
      containers:
        - name: kromgo
          image: ghcr.io/kashalls/kromgo:latest@sha256:50b1477c479d0eec59aa008ec9ca7ad28595ec1e6cc3fb4a31643209e0ec0f85
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: config
              mountPath: /kromgo/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: kromgo-configmap
