apiVersion: apps/v1
kind: Deployment
metadata:
  name: kromgo
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: kromgo
  replicas: 1
  template:
    metadata:
      labels:
        app: kromgo
    spec:
      containers:
        - name: kromgo
          image: ghcr.io/kashalls/kromgo:latest@sha256:bd2213c7e471ada38bfec5600f17ede76177815d560d2d6b9a0f433054c93080
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: config
              mountPath: /kromgo/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: kromgo-configmap
