apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  labels:
    app: litellm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
        - name: litellm
          env:
            - name: CONFIG_FILE_PATH
              value: /app/config.yaml
            - name: LITELLM_LOG
              value: DEBUG
          envFrom:
            - secretRef:
                name: litellm-secret
          image: ghcr.io/berriai/litellm:main-stable@sha256:b959a1816fa454a14d2842242d0fa1cd0d39f96fc94d3a1f4e1de4e48e2398c6
          ports:
            - containerPort: 4000
              name: http
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: litellm-config
