model_list:
  - model_name: nutritrace-default
    litellm_params:
      model: bedrock/mantle/anthropic.claude-sonnet-5-5
      aws_region_name: eu-west-1
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      #aws_bedrock_project_id: proj_6ndw24kw5sktspomktbl
    model_info:
      supports_vision: True
  - model_name: claude-opus-latest
    litellm_params:
      model: os.environ/CLAUDE_OPUS_LATEST_INF_ARN
      aws_region_name: eu-west-1
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      requestMetadata:
        Application: "LiteLLM"
  - model_name: claude-sonnet-latest
    litellm_params:
      model: os.environ/CLAUDE_SONNET_LATEST_INF_ARN
      aws_region_name: eu-west-1
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      requestMetadata:
        Application: "LiteLLM"
  - model_name: claude-haiku-latest
    litellm_params:
      model: os.environ/CLAUDE_HAIKU_LATEST_INF_ARN
      aws_region_name: eu-west-1
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      requestMetadata:
        Application: "LiteLLM"
    model_info:
      supports_vision: True
  - model_name: openai-luna-latest
    litellm_params:
      model: bedrock/global.openai.gpt-6-luna
      aws_region_name: eu-west-1
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
    model_info:
      supports_vision: True
  - model_name: amazon-titan-embed-text-v2
    litellm_params:
      model: bedrock/amazon.titan-embed-text-v2:0
      aws_region_name: eu-west-1
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY

router_settings:
  fallbacks:
    [{ "nutritrace-default": ["claude-opus-5", "claude-haiku-latest"] }]
