apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

images:
  - name: app
    newName: eclipse-mosquitto
    newTag: 2.0.22@sha256:05b5c328c11046613c4b8137b27021c15342c9fc90ae9c2f4750ed3ece5967bd

namespace: smarthome

configMapGenerator:
  - name: env-configmap
    namespace: smarthome
    literals:
      - TZ=Europe/Amsterdam
  - name: mosquitto-configmap
    files:
      - mosquitto.conf=./resources/mosquitto.conf

namePrefix: mosquitto-

labels:
  - includeSelectors: true
    pairs:
      app: mosquitto
  - pairs:
      app.kubernetes.io/name: mosquitto

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: mosquitto
    target:
      kind: Deployment
      name: deployment
  - target:
      kind: Ingress
    patch: |
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: ingress
