apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: intel-device-plugins

helmCharts:
  - name: intel-device-plugins-operator
    repo: https://intel.github.io/helm-charts/
    version: 0.37.0
    releaseName: intel-device-plugins-operator
    namespace: intel-device-plugins
    includeCRDs: true

resources:
  - ns.yaml

patches:
  - target:
      kind: MutatingWebhookConfiguration
      name: inteldeviceplugins-mutating-webhook-configuration
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1compare-options
        value: ServerSideDiff=false
  - target:
      kind: ValidatingWebhookConfiguration
      name: inteldeviceplugins-validating-webhook-configuration
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1compare-options
        value: ServerSideDiff=false
