apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-inspector
  namespace: mcp-inspector
  labels:
    app: mcp-inspector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-inspector
  template:
    metadata:
      labels:
        app: mcp-inspector
    spec:
      containers:
        - name: mcp-inspector
          image: ghcr.io/modelcontextprotocol/inspector:latest@sha256:574567ba5f9f37c6b3f329af8fd6abdb77e21978f41bda11bea8e8adb070fe67
          ports:
            - containerPort: 6274
              name: client
            - containerPort: 6277
              name: server
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "6274"
            - name: DANGEROUSLY_OMIT_AUTH
              value: "true"
