apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-inspector
  namespace: mcp-inspector
  labels:
    app: mcp-inspector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-inspector
  template:
    metadata:
      labels:
        app: mcp-inspector
    spec:
      containers:
        - name: mcp-inspector
          image: ghcr.io/modelcontextprotocol/inspector:latest@sha256:438fe7792332ae29d629b4d723856c8d8956bed57abc98a473bed043257393f1
          ports:
            - containerPort: 6274
              name: client
            - containerPort: 6277
              name: server
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "6274"
            - name: DANGEROUSLY_OMIT_AUTH
              value: "true"
