apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-inspector
  namespace: mcp-inspector
  labels:
    app: mcp-inspector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-inspector
  template:
    metadata:
      labels:
        app: mcp-inspector
    spec:
      containers:
        - name: mcp-inspector
          image: ghcr.io/modelcontextprotocol/inspector:latest@sha256:4575d658b59e47e4e9f7c6abc1d4eafd40a68e6adc7aac600001262436864e12
          ports:
            - containerPort: 6274
              name: client
            - containerPort: 6277
              name: server
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "6274"
            - name: DANGEROUSLY_OMIT_AUTH
              value: "true"
