apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dvr

resources:
  - ../../base/

images:
  - name: app
    newName: ghcr.io/linuxserver/prowlarr
    newTag: latest@sha256:f9151e5bc1025c6d0a630d503210cdcb6bb55a7cc098562609d96a408d838902

configMapGenerator:
  - name: env-configmap
    literals:
      - PUID=911
      - PGID=911
      - TZ=Europe/Amsterdam

namePrefix: prowlarr-

labels:
  - includeSelectors: true
    pairs:
      app: prowlarr
  - pairs:
      app.kubernetes.io/name: prowlarr

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
  - path: ingress-patch.yaml
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: prowlarr
    target:
      kind: Deployment
      name: deployment
