apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dvr

resources:
  - ../../base/

images:
  - name: app
    newName: ghcr.io/linuxserver/prowlarr
    newTag: latest@sha256:a8fe7b9c502f979146b6d0f22438b825c38e068241bb8a708c473062dffdbb03

configMapGenerator:
  - name: env-configmap
    literals:
      - PUID=911
      - PGID=911
      - TZ=Europe/Amsterdam

namePrefix: prowlarr-

labels:
  - includeSelectors: true
    pairs:
      app: prowlarr

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
  - path: ingress-patch.yaml
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: prowlarr
    target:
      kind: Deployment
      name: deployment
