apiVersion: apps/v1
kind: Deployment
metadata:
  name: rutorrent-deployment
  namespace: dvr
  labels:
    app: rutorrent
    argocd.argoproj.io/instance: rutorrent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rutorrent
  template:
    metadata:
      labels:
        app: rutorrent
    spec:
      containers:
        - name: rutorrent
          envFrom:
            - configMapRef:
                name: rutorrent-envs
          image: ghcr.io/crazy-max/rtorrent-rutorrent:latest@sha256:db63539cacdba7324a37f66303055c8cf7ed35f9ec44127e759ed9d27b75e4d8
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /usr/local/bin/healthcheck
            initialDelaySeconds: 600
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
          ports:
            - name: http
              containerPort: 8080
            - name: xmlrpc
              containerPort: 8000
            - name: rtorrent
              containerPort: 51413
            - name: dht
              containerPort: 6881
          volumeMounts:
            - name: downloads
              mountPath: /downloads
            - name: config
              mountPath: /data
              subPath: rtorrent-config
            - name: temporary-rundir
              mountPath: /var/run/rtorrent
        - name: flood
          image: jesec/flood:latest@sha256:26e66e480ca7a044ad8cd4ac191c2967db2e5eaf584a0d749b83fd0a230b7fc4
          args: ["--allowedpath", "/data", "--allowedpath", "/var/run/rtorrent"]
          securityContext:
            runAsUser: 911
            runAsGroup: 911
          envFrom:
            - configMapRef:
                name: flood-envs
          ports:
            - containerPort: 3000
              name: http-flood
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /data
              subPath: rtorrent-config
            - name: temporary-rundir
              mountPath: /var/run/rtorrent
      volumes:
        - name: downloads
          hostPath:
            path: /downloads
            type: DirectoryOrCreate
        - name: config
          hostPath:
            path: /config
            type: DirectoryOrCreate
        - name: temporary-rundir
          emptyDir: {}
