apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id
  namespace: pocket-id
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: pocket-id
    template:
      engineVersion: v2
      data:
        ENCRYPTION_KEY: "{{ .encryptionKey }}"
  dataFrom:
    - extract:
        key: k8s-homelab-secrets
        property: pocketid
