apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mcp-gateway

resources:
  - ns.yaml
  - external-secret.yaml
  - gateway.yaml
  - httproute.yaml
  - backend.yaml
  - supergateway-karakeep.yaml
  - ingress.yaml
