apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dvr

resources:
  - ../../base/
  - ./ingress-ext.yaml

images:
  - name: app
    newName: ghcr.io/linuxserver/jellyfin
    newTag: latest@sha256:ae1ac3d89b8598f31f5e1dc5aff898e13eab617303db58f84956e26f7b78c198

configMapGenerator:
  - name: env-configmap
    literals:
      - JELLYFIN_PublishedServerUrl=https://jf.lab.javydekoning.com
      - TZ=Europe/Amsterdam

namePrefix: jellyfin-

labels:
  - includeSelectors: true
    pairs:
      app: jellyfin

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
  - path: ingress-patch.yaml
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: jellyfin
    target:
      kind: Deployment
      name: deployment
