apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dvr

resources:
  - ../../base/
  - ./ingress-ext.yaml

images:
  - name: app
    newName: ghcr.io/linuxserver/jellyfin
    newTag: latest@sha256:7351868a3a340049503d25da65fae19c77ce3ea58f607f702cac65b6faeec898

configMapGenerator:
  - name: env-configmap
    literals:
      - JELLYFIN_PublishedServerUrl=https://jf.lab.javydekoning.com
      - TZ=Europe/Amsterdam

namePrefix: jellyfin-

labels:
  - includeSelectors: true
    pairs:
      app: jellyfin

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
  - path: ingress-patch.yaml
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: jellyfin
    target:
      kind: Deployment
      name: deployment
