apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qbittorrent

resources:
  - ../../base/

nameSuffix: -main

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/hostPath/path
        value: /config/qbit-main
    target:
      kind: Deployment
      name: qbittorrent
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: qbittorrent
      spec:
        template:
          metadata:
            labels:
              app.kubernetes.io/name: qbittorrent-main
    target:
      kind: Deployment
      name: qbittorrent

labels:
  - includeSelectors: true
    pairs:
      app: qbittorrent-main
  - pairs:
      app.kubernetes.io/name: qbittorrent-main
