apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-freshrss-secret
  namespace: freshrss
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: freshrss-credentials
    template:
      engineVersion: v2
      data:
        OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        OIDC_CLIENT_CRYPTO_KEY: "{{ .OIDC_CLIENT_CRYPTO_KEY }}"
  dataFrom:
    - extract:
        key: k8s-homelab-secrets
        property: freshrss
