apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zigbee2mqtt
    spec:
      containers:
        - name: app
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: persistence
              mountPath: /app/data
              subPath: zigbee2mqtt
            - name: usb
              mountPath: /dev/ttyUSB0
            - name: udev
              mountPath: /run/udev
        - name: zigbee2mqtt-exporter
          image: ghcr.io/d0ugal/zigbee2mqtt-exporter:latest@sha256:f6f341d94145f6631288952b0480a05d81d5866b543982db4c110ef6b0c9dfd4
          ports:
            - name: metrics
              containerPort: 8087
          env:
            - name: Z2M_EXPORTER_WEBSOCKET_URL
              value: "ws://localhost:8080/api"
            - name: Z2M_EXPORTER_LOG_LEVEL
              value: "info"
      volumes:
        - name: usb
          hostPath:
            path: /dev/ttyUSB0
        - name: udev
          hostPath:
            path: /run/udev
