apiVersion: apps/v1
kind: Deployment
metadata:
  name: evcc
  labels:
    app: evcc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evcc
  template:
    metadata:
      labels:
        app: evcc
    spec:
      containers:
        - name: evcc
          image: evcc/evcc:latest@sha256:e96033e245d332b393546a965ed10d27d3a4495c0db06a60b9be851504f759b6
          command:
            - evcc
          ports:
            - containerPort: 7070
              name: http
            - containerPort: 8887
              name: udp
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /etc/evcc.yaml
              subPath: evcc.yaml
            - name: data
              mountPath: /root/.evcc
      volumes:
        - name: config
          configMap:
            name: evcc-config
        - name: data
          hostPath:
            path: /config/evcc
            type: DirectoryOrCreate
