apiVersion: apps/v1
kind: Deployment
metadata:
  name: evcc
  labels:
    app: evcc
    app.kubernetes.io/name: evcc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evcc
  template:
    metadata:
      labels:
        app: evcc
        app.kubernetes.io/name: evcc
    spec:
      containers:
        - name: evcc
          image: evcc/evcc:latest@sha256:42bf170708f99f009767dcb0eb1f38c74bb35d5c635824ec90b87784ee20580b
          command:
            - evcc
          ports:
            - containerPort: 7070
              name: http
            - containerPort: 8887
              name: udp
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /etc/evcc.yaml
              subPath: evcc.yaml
            - name: data
              mountPath: /root/.evcc
      volumes:
        - name: config
          configMap:
            name: evcc-config
        - name: data
          hostPath:
            path: /config/evcc
            type: DirectoryOrCreate
