apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui
  namespace: openwebui
  labels:
    app: openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwebui
  template:
    metadata:
      labels:
        app: openwebui
    spec:
      containers:
        - name: openwebui
          image: ghcr.io/open-webui/open-webui:main@sha256:1e834205e71a97812c8e3e8cbf05e7ab40887143a65aa78b85fe7930d5892f0d
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name: openwebui-secret
            - configMapRef:
                name: openwebui-config
            - configMapRef:
                name: openwebui-file-config
          volumeMounts:
            - name: openwebui-data
              mountPath: /app/backend/data
      volumes:
        - name: openwebui-data
          hostPath:
            path: /config/openwebui-data
            type: DirectoryOrCreate
