apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui
  namespace: openwebui
  labels:
    app: openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwebui
  template:
    metadata:
      labels:
        app: openwebui
    spec:
      containers:
        - name: openwebui
          image: ghcr.io/open-webui/open-webui:main@sha256:b8095f79a6a8ffad8f830bdacc9b5b0aef805689b31bca0b065cc2424d3cfaeb
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name: openwebui-secret
            - configMapRef:
                name: openwebui-config
            - configMapRef:
                name: openwebui-file-config
          volumeMounts:
            - name: openwebui-data
              mountPath: /app/backend/data
      volumes:
        - name: openwebui-data
          hostPath:
            path: /config/openwebui-data
            type: DirectoryOrCreate
